name: Reusable Helm test

on:
  workflow_call:
    inputs:
      chart_directory:
        description: Path to the Helm chart in the calling repository.
        required: true
        type: string
      timeout:
        description: Maximum time, in minutes, for this job.
        required: false
        default: 10
        type: number
      helm_container:
        description: The container image to use for Helm testing.
        required: false
        default: "alpine/helm 
jobs:
  lint-and-render:
    runs-on: self-hosted
    container: "${{ inputs.helm_container }}"
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Verify Helm on Azure VM runner
        shell: powershell
        run: |
         hostname
         whoami
         helm version

      - uses: actions/checkout@v4

      - name: Lint chart
        run: helm lint "${{ inputs.chart_directory }}"

      - name: Render Kubernetes manifests
        run: helm template voting-app "${{ inputs.chart_directory }}" --namespace default --debug > rendered-manifests.yaml

      - name: Upload rendered manifests
        uses: actions/upload-artifact@v4
        with:
          name: rendered-manifests
          path: rendered-manifests.yaml
          if-no-files-found: error
